apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metrics-h24-grp1-eq10
  template:
    metadata:
      labels:
        app: metrics-h24-grp1-eq10
    spec:
      containers:
      - name: metrics-h24-grp1-eq10
        image: eq110/metrics-h24-grp1-eq10:latest
        ports:
            - containerPort: 3000
        envFrom:
        - secretRef:
            name: metrics
        - configMapRef:
            name: metrics
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
