apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-cronjob
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metrics-cronjob-h24-gr1-eq10
  template:
    metadata:
      labels:
        app: metrics-cronjob-h24-gr1-eq10
    spec:
      containers:
      - name: metrics-cronjob-h24-gr1-eq10
        image: eq110/metrics-cronjob-h24-grp1-eq10:latest
        resources:
          limits:
            cpu: 50m
            memory: 256Mi
          requests:
            cpu: 25m
            memory: 128Mi